openapi: 3.1.0
info:
  title: k-v.io key-value store API definition
  version: 0.0.1
paths:
  "/v0/key/{key}":
    parameters:
    - "$ref": "#/components/parameters/keyParam"
    get:
      summary: Retrieve a key's value
      description: Retrieve a key's value
      responses:
        "200":
          "$ref": "#/components/responses/OK"
        "400":
          "$ref": "#/components/responses/BadRequest"
        "404":
          "$ref": "#/components/responses/NotFound"
        "503":
          "$ref": "#/components/responses/ServiceUnavailable"
    put:
      summary: Set (or create) a key's value
      description: Set (or create) a key's value
      responses:
        "204":
          "$ref": "#/components/responses/NoContent"
        "400":
          "$ref": "#/components/responses/BadRequest"
        "503":
          "$ref": "#/components/responses/ServiceUnavailable"
    delete:
      summary: Delete a key and value
      description: Delete a key and value
      responses:
        "204":
          "$ref": "#/components/responses/NoContent"
        "400":
          "$ref": "#/components/responses/BadRequest"
        "503":
          "$ref": "#/components/responses/ServiceUnavailable"
components:
  schemas:
    key:
      type: string
      minLength: 1
      maxLength: 1023
      description:
        This is the key used to lookup the value
    value:
      type: string
      minLength: 0 # You can have a null value
      maxLength: 1023
      description:
        This is the value associated with the key
  parameters:
    keyParam:
      name: key
      in: path
      required: true
      schema:
        "$ref": "#/components/schemas/key"
  responses:
      OK:
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: value
                  description: The key's value
      NoContent:
        description: No Content
      NotFound:
        description: Not Found
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: A descriptive error message
      BadRequest:
        description: Bad Request
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: A descriptive error message
      ServiceUnavailable:
        description: Service Unavailable
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: A descriptive error message
