/*
 * k-v.io key-value store API definition
 *
 * A REST-based key-value store built with Golang layered on etcd
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"V0KeyKeyDelete",
		strings.ToUpper("Delete"),
		"/v0/key/{key}",
		V0KeyKeyDelete,
	},

	Route{
		"V0KeyKeyGet",
		strings.ToUpper("Get"),
		"/v0/key/{key}",
		V0KeyKeyGet,
	},

	Route{
		"V0KeyKeyPut",
		strings.ToUpper("Put"),
		"/v0/key/{key}",
		V0KeyKeyPut,
	},
}
